name: CI

on:
  push:
    branches: [ master ]
jobs:
 jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: jenkinsfile-runner-prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
